# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ranking_service_pb2 as ranking__service__pb2


class RankingServiceStub(object):
    """============================================
    Ranking Service - Ранжирование и векторный поиск
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateEmbedding = channel.unary_unary(
                '/ranking_service.RankingService/GenerateEmbedding',
                request_serializer=ranking__service__pb2.GenerateEmbeddingRequest.SerializeToString,
                response_deserializer=ranking__service__pb2.EmbeddingResponse.FromString,
                )
        self.GenerateBatchEmbeddings = channel.unary_unary(
                '/ranking_service.RankingService/GenerateBatchEmbeddings',
                request_serializer=ranking__service__pb2.GenerateBatchEmbeddingsRequest.SerializeToString,
                response_deserializer=ranking__service__pb2.BatchEmbeddingsResponse.FromString,
                )
        self.RankContentForUser = channel.unary_unary(
                '/ranking_service.RankingService/RankContentForUser',
                request_serializer=ranking__service__pb2.RankContentRequest.SerializeToString,
                response_deserializer=ranking__service__pb2.RankedContentResponse.FromString,
                )
        self.CalculateRelevance = channel.unary_unary(
                '/ranking_service.RankingService/CalculateRelevance',
                request_serializer=ranking__service__pb2.CalculateRelevanceRequest.SerializeToString,
                response_deserializer=ranking__service__pb2.RelevanceResponse.FromString,
                )
        self.FindSimilarContent = channel.unary_unary(
                '/ranking_service.RankingService/FindSimilarContent',
                request_serializer=ranking__service__pb2.FindSimilarContentRequest.SerializeToString,
                response_deserializer=ranking__service__pb2.SimilarContentResponse.FromString,
                )
        self.UpdateUserInterestsFromFeedback = channel.unary_unary(
                '/ranking_service.RankingService/UpdateUserInterestsFromFeedback',
                request_serializer=ranking__service__pb2.UpdateInterestsRequest.SerializeToString,
                response_deserializer=ranking__service__pb2.UpdateInterestsResponse.FromString,
                )


class RankingServiceServicer(object):
    """============================================
    Ranking Service - Ранжирование и векторный поиск
    ============================================

    """

    def GenerateEmbedding(self, request, context):
        """Генерация эмбеддингов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateBatchEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RankContentForUser(self, request, context):
        """Ранжирование контента
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateRelevance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindSimilarContent(self, request, context):
        """Векторный поиск
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserInterestsFromFeedback(self, request, context):
        """Обновление профиля пользователя на основе обратной связи
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=ranking__service__pb2.GenerateEmbeddingRequest.FromString,
                    response_serializer=ranking__service__pb2.EmbeddingResponse.SerializeToString,
            ),
            'GenerateBatchEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateBatchEmbeddings,
                    request_deserializer=ranking__service__pb2.GenerateBatchEmbeddingsRequest.FromString,
                    response_serializer=ranking__service__pb2.BatchEmbeddingsResponse.SerializeToString,
            ),
            'RankContentForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RankContentForUser,
                    request_deserializer=ranking__service__pb2.RankContentRequest.FromString,
                    response_serializer=ranking__service__pb2.RankedContentResponse.SerializeToString,
            ),
            'CalculateRelevance': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateRelevance,
                    request_deserializer=ranking__service__pb2.CalculateRelevanceRequest.FromString,
                    response_serializer=ranking__service__pb2.RelevanceResponse.SerializeToString,
            ),
            'FindSimilarContent': grpc.unary_unary_rpc_method_handler(
                    servicer.FindSimilarContent,
                    request_deserializer=ranking__service__pb2.FindSimilarContentRequest.FromString,
                    response_serializer=ranking__service__pb2.SimilarContentResponse.SerializeToString,
            ),
            'UpdateUserInterestsFromFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserInterestsFromFeedback,
                    request_deserializer=ranking__service__pb2.UpdateInterestsRequest.FromString,
                    response_serializer=ranking__service__pb2.UpdateInterestsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ranking_service.RankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RankingService(object):
    """============================================
    Ranking Service - Ранжирование и векторный поиск
    ============================================

    """

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ranking_service.RankingService/GenerateEmbedding',
            ranking__service__pb2.GenerateEmbeddingRequest.SerializeToString,
            ranking__service__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateBatchEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ranking_service.RankingService/GenerateBatchEmbeddings',
            ranking__service__pb2.GenerateBatchEmbeddingsRequest.SerializeToString,
            ranking__service__pb2.BatchEmbeddingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RankContentForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ranking_service.RankingService/RankContentForUser',
            ranking__service__pb2.RankContentRequest.SerializeToString,
            ranking__service__pb2.RankedContentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculateRelevance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ranking_service.RankingService/CalculateRelevance',
            ranking__service__pb2.CalculateRelevanceRequest.SerializeToString,
            ranking__service__pb2.RelevanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindSimilarContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ranking_service.RankingService/FindSimilarContent',
            ranking__service__pb2.FindSimilarContentRequest.SerializeToString,
            ranking__service__pb2.SimilarContentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUserInterestsFromFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ranking_service.RankingService/UpdateUserInterestsFromFeedback',
            ranking__service__pb2.UpdateInterestsRequest.SerializeToString,
            ranking__service__pb2.UpdateInterestsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
