# Основные настройки
loopback_users.guest = false
listeners.tcp.default = 5672
management.tcp.port = 15672

# Загрузка определений при старте
management.load_definitions = /etc/rabbitmq/definitions.json

# Логирование
log.file.level = info
log.console = true
log.console.level = info